/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class CustomerMngWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount account;
    /**
     * Creates new form CustomerManagementScreen
     */
    public CustomerMngWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount account) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.account=account;
        
        this.populate();
    }
    
    public void populate()
    {
        DefaultTableModel dtm = (DefaultTableModel) tabRestaurants.getModel();
        dtm.setRowCount(0);
        for (Restaurant i : this.ecosystem.getRestaurantDirectory().getRestaurantList()) {
            
                Object row[] = new Object[2];
                row[0] = i;
                row[1] = i.getRestaurantInfo();
                dtm.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewMenu = new javax.swing.JButton();
        btnViewOrders = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabRestaurants = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewMenu.setFont(new java.awt.Font("宋体", 3, 14)); // NOI18N
        btnViewMenu.setText("View all menus");
        btnViewMenu.setToolTipText("");
        btnViewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMenuActionPerformed(evt);
            }
        });
        add(btnViewMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 252, 163, -1));

        btnViewOrders.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btnViewOrders.setText("View all orders");
        btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrdersActionPerformed(evt);
            }
        });
        add(btnViewOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 304, 207, -1));

        tabRestaurants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of the Restauant", "Restautant brief Info"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabRestaurants);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 131, 510, 96));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Select a Restaurant");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 12, -1, 32));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMenuActionPerformed
        int selectedRow = tabRestaurants.getSelectedRow();
        
        if (selectedRow >= 0) {
            Restaurant res=(Restaurant)tabRestaurants.getValueAt(selectedRow, 0);
            ViewMenus view=new ViewMenus(this.userProcessContainer,this.ecosystem,this.account.getUsername(),res.getRestaurantName());
            this.userProcessContainer.add("ViewMenus",view);
            CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
            layout.show(this.userProcessContainer, "ViewMenus");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_btnViewMenuActionPerformed

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabRestaurants.getSelectedRow();
        
        if (selectedRow >= 0) {
            Restaurant res=(Restaurant)tabRestaurants.getValueAt(selectedRow, 0);
            ViewOrders view=new ViewOrders(this.userProcessContainer,this.ecosystem,res.getRestaurantName(),this.account.getUsername());
            this.userProcessContainer.add("ViewOrders",view);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.show(this.userProcessContainer, "ViewOrders");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }

    }//GEN-LAST:event_btnViewOrdersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewMenu;
    private javax.swing.JButton btnViewOrders;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabRestaurants;
    // End of variables declaration//GEN-END:variables
}
