/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Person.Profile;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    private Profile profile;
    public CreatePanel(Profile profile) {
        initComponents();
        this.profile=profile;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateYourProfile = new javax.swing.JLabel();
        lblDateofbirth = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeographicdata = new javax.swing.JLabel();
        lblFAXnumber = new javax.swing.JLabel();
        lblEmailaddresses = new javax.swing.JLabel();
        lblSocialSecuritynumber = new javax.swing.JLabel();
        lblMedicalrecordnumber = new javax.swing.JLabel();
        lblHealthplanbeneficiarynumber = new javax.swing.JLabel();
        lblBankaccountnumbers = new javax.swing.JLabel();
        lblTelephonenumbers = new javax.swing.JLabel();
        lblCertificatelicensenumber = new javax.swing.JLabel();
        lblVehicleidentifiersandserialnumbersincludinglicenseplates = new javax.swing.JLabel();
        lblDeviceidentifiersandserialnumbers = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblInternetprotocoladdresses = new javax.swing.JLabel();
        lblAnyuniqueidentifyingnumber = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeographicdata = new javax.swing.JTextField();
        txtDateofbirth = new javax.swing.JTextField();
        txtTelephonenumbers = new javax.swing.JTextField();
        txtFAXnumber = new javax.swing.JTextField();
        txtEmailaddresses = new javax.swing.JTextField();
        txtSocialSecuritynumber = new javax.swing.JTextField();
        txtMedicalrecordnumber = new javax.swing.JTextField();
        txtHealthplanbeneficiarynumber = new javax.swing.JTextField();
        txtBankaccountnumbers = new javax.swing.JTextField();
        txtCertificatelicensenumber = new javax.swing.JTextField();
        txtVehicleidentifiersandserialnumbersincludinglicenseplates = new javax.swing.JTextField();
        txtDeviceidentifiersandserialnumbers = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtInternetprotocoladdresses = new javax.swing.JTextField();
        txtAnyuniqueidentifyingnumber = new javax.swing.JTextField();
        btnPhoto = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        lblBiometric_identifiers = new javax.swing.JLabel();
        txtBiometricidentifiers = new javax.swing.JTextField();
        txtphotopath = new javax.swing.JTextField();

        lblCreateYourProfile.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        lblCreateYourProfile.setForeground(new java.awt.Color(255, 51, 51));
        lblCreateYourProfile.setText("Create Your Profile");

        lblDateofbirth.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblDateofbirth.setText("Date of birth");

        lblName.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblName.setText("Name");

        lblGeographicdata.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblGeographicdata.setText("Geographic data");

        lblFAXnumber.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblFAXnumber.setText("FAX number");

        lblEmailaddresses.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblEmailaddresses.setText("Email addresses");

        lblSocialSecuritynumber.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblSocialSecuritynumber.setText("Social Security number");

        lblMedicalrecordnumber.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblMedicalrecordnumber.setText("Medical record number");

        lblHealthplanbeneficiarynumber.setText("Health plan beneficiary number");

        lblBankaccountnumbers.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblBankaccountnumbers.setText("Bank account numbers");

        lblTelephonenumbers.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblTelephonenumbers.setText("Telephone numbers");

        lblCertificatelicensenumber.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblCertificatelicensenumber.setText("Certificate/license number");

        lblVehicleidentifiersandserialnumbersincludinglicenseplates.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblVehicleidentifiersandserialnumbersincludinglicenseplates.setText("Vehicle identifiers and serial numbers including license plates");

        lblDeviceidentifiersandserialnumbers.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblDeviceidentifiersandserialnumbers.setText("Device identifiers and serial numbers");

        lblLinkedIn.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblLinkedIn.setText("LinkedIn");

        lblInternetprotocoladdresses.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblInternetprotocoladdresses.setText("Internet protocol addresses");

        lblAnyuniqueidentifyingnumber.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblAnyuniqueidentifyingnumber.setText("Any unique identifying number, characteristic, or code");

        txtHealthplanbeneficiarynumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthplanbeneficiarynumberActionPerformed(evt);
            }
        });

        txtCertificatelicensenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificatelicensenumberActionPerformed(evt);
            }
        });

        btnPhoto.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        btnPhoto.setText("Import Your Full Photo");
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        image.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        image.setText("FullFacePhoto");

        lblBiometric_identifiers.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblBiometric_identifiers.setText("Biometric identifiers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDateofbirth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDateofbirth))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblGeographicdata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTelephonenumbers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelephonenumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFAXnumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFAXnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEmailaddresses)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmailaddresses))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSocialSecuritynumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSocialSecuritynumber))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblMedicalrecordnumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMedicalrecordnumber))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnPhoto))
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(txtphotopath, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHealthplanbeneficiarynumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHealthplanbeneficiarynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblAnyuniqueidentifyingnumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAnyuniqueidentifyingnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblInternetprotocoladdresses)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtInternetprotocoladdresses))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblLinkedIn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtLinkedIn))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDeviceidentifiersandserialnumbers)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDeviceidentifiersandserialnumbers))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblVehicleidentifiersandserialnumbersincludinglicenseplates)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtVehicleidentifiersandserialnumbersincludinglicenseplates))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCertificatelicensenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCertificatelicensenumber)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBankaccountnumbers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBankaccountnumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCreateYourProfile)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBiometric_identifiers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBiometricidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 53, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDateofbirth, lblEmailaddresses, lblFAXnumber, lblGeographicdata, lblMedicalrecordnumber, lblSocialSecuritynumber, lblTelephonenumbers});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAnyuniqueidentifyingnumber, lblBankaccountnumbers, lblBiometric_identifiers, lblCertificatelicensenumber, lblDeviceidentifiersandserialnumbers, lblHealthplanbeneficiarynumber, lblInternetprotocoladdresses, lblLinkedIn, lblVehicleidentifiersandserialnumbersincludinglicenseplates});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAnyuniqueidentifyingnumber, txtBankaccountnumbers, txtBiometricidentifiers, txtCertificatelicensenumber, txtDeviceidentifiersandserialnumbers, txtHealthplanbeneficiarynumber, txtInternetprotocoladdresses, txtLinkedIn, txtVehicleidentifiersandserialnumbersincludinglicenseplates});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCreateYourProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHealthplanbeneficiarynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHealthplanbeneficiarynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGeographicdata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBankaccountnumbers)
                        .addComponent(txtBankaccountnumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCertificatelicensenumber)
                        .addComponent(txtCertificatelicensenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephonenumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelephonenumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehicleidentifiersandserialnumbersincludinglicenseplates)
                    .addComponent(txtVehicleidentifiersandserialnumbersincludinglicenseplates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFAXnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFAXnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeviceidentifiersandserialnumbers)
                    .addComponent(txtDeviceidentifiersandserialnumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailaddresses, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailaddresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedIn)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSocialSecuritynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSocialSecuritynumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInternetprotocoladdresses)
                    .addComponent(txtInternetprotocoladdresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalrecordnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicalrecordnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnyuniqueidentifyingnumber)
                    .addComponent(txtAnyuniqueidentifyingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBiometric_identifiers)
                            .addComponent(txtBiometricidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addComponent(txtphotopath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnPhoto))
                    .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDateofbirth, lblEmailaddresses, lblFAXnumber, lblGeographicdata, lblMedicalrecordnumber, lblName, lblSocialSecuritynumber, lblTelephonenumbers, txtDateofbirth, txtEmailaddresses, txtFAXnumber, txtGeographicdata, txtMedicalrecordnumber, txtName, txtSocialSecuritynumber, txtTelephonenumbers});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAnyuniqueidentifyingnumber, lblBankaccountnumbers, lblBiometric_identifiers, lblCertificatelicensenumber, lblDeviceidentifiersandserialnumbers, lblHealthplanbeneficiarynumber, lblInternetprotocoladdresses, lblLinkedIn, lblVehicleidentifiersandserialnumbersincludinglicenseplates});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAnyuniqueidentifyingnumber, txtBankaccountnumbers, txtBiometricidentifiers, txtCertificatelicensenumber, txtDeviceidentifiersandserialnumbers, txtHealthplanbeneficiarynumber, txtInternetprotocoladdresses, txtLinkedIn, txtVehicleidentifiersandserialnumbersincludinglicenseplates});

    }// </editor-fold>//GEN-END:initComponents

    private void txtCertificatelicensenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificatelicensenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificatelicensenumberActionPerformed

    private void txtHealthplanbeneficiarynumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthplanbeneficiarynumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthplanbeneficiarynumberActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        profile.setName(txtName.getText());
        profile.setGeographic_data(txtGeographicdata.getText());
        profile.setDate_of_birth(txtDateofbirth.getText());
        profile.setTelephone_num(txtTelephonenumbers.getText());
        profile.setFAX_num(txtFAXnumber.getText());
        profile.setEmail_address(txtEmailaddresses.getText());
        profile.setSocialSecurity_num(txtSocialSecuritynumber.getText());
        profile.setMedicalrecord_num(txtMedicalrecordnumber.getText());
        profile.setHealth_plan_beneficiary_num(txtHealthplanbeneficiarynumber.getText());
        profile.setBankaccount_num(txtBankaccountnumbers.getText());
        profile.setCertificate_license_num(txtCertificatelicensenumber.getText());
        profile.setVehicle_id(txtVehicleidentifiersandserialnumbersincludinglicenseplates.getText());
        profile.setDevice_id(txtDeviceidentifiersandserialnumbers.getText());
        profile.setLinkedIn(txtLinkedIn.getText());
        profile.setInternet_protocol_addresses(txtInternetprotocoladdresses.getText());
        profile.setAny_unique_identifying_number_characteristic_or_code(txtAnyuniqueidentifyingnumber.getText());
        profile.setBiometric_identifiers(txtBiometricidentifiers.getText());
        profile.setPhotopath(txtphotopath.getText());
        //Prompt user that product was successfully created
        JOptionPane.showMessageDialog(null,"Create Profile Successfully");
    }//GEN-LAST:event_btnCreateActionPerformed
   
    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File file=chooser.getSelectedFile();
         String path=file.getAbsolutePath();
        txtphotopath.setText(path);
        
        ImageIcon ii=new ImageIcon(path);
        image.setIcon(ii);
    }//GEN-LAST:event_btnPhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnPhoto;
    private javax.swing.JLabel image;
    private javax.swing.JLabel lblAnyuniqueidentifyingnumber;
    private javax.swing.JLabel lblBankaccountnumbers;
    private javax.swing.JLabel lblBiometric_identifiers;
    private javax.swing.JLabel lblCertificatelicensenumber;
    private javax.swing.JLabel lblCreateYourProfile;
    private javax.swing.JLabel lblDateofbirth;
    private javax.swing.JLabel lblDeviceidentifiersandserialnumbers;
    private javax.swing.JLabel lblEmailaddresses;
    private javax.swing.JLabel lblFAXnumber;
    private javax.swing.JLabel lblGeographicdata;
    private javax.swing.JLabel lblHealthplanbeneficiarynumber;
    private javax.swing.JLabel lblInternetprotocoladdresses;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalrecordnumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSocialSecuritynumber;
    private javax.swing.JLabel lblTelephonenumbers;
    private javax.swing.JLabel lblVehicleidentifiersandserialnumbersincludinglicenseplates;
    private javax.swing.JTextField txtAnyuniqueidentifyingnumber;
    private javax.swing.JTextField txtBankaccountnumbers;
    private javax.swing.JTextField txtBiometricidentifiers;
    private javax.swing.JTextField txtCertificatelicensenumber;
    private javax.swing.JTextField txtDateofbirth;
    private javax.swing.JTextField txtDeviceidentifiersandserialnumbers;
    private javax.swing.JTextField txtEmailaddresses;
    private javax.swing.JTextField txtFAXnumber;
    private javax.swing.JTextField txtGeographicdata;
    private javax.swing.JTextField txtHealthplanbeneficiarynumber;
    private javax.swing.JTextField txtInternetprotocoladdresses;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalrecordnumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSocialSecuritynumber;
    private javax.swing.JTextField txtTelephonenumbers;
    private javax.swing.JTextField txtVehicleidentifiersandserialnumbersincludinglicenseplates;
    private javax.swing.JTextField txtphotopath;
    // End of variables declaration//GEN-END:variables

    
}
