/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Person.Profile;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;


/**
 *
 * @author User
 */
public class ViewPanel extends javax.swing.JPanel {

   

    /**
     * Creates new form ViewPanel
     * @param profile
     */
   
    public ViewPanel(Profile profile) {
        initComponents();
        displayProfile(profile);
    }
private void displayProfile(Profile profile) {
        String profileName=profile.getName();
        txtName.setText(profileName);
    
    String profileGeographic_data=profile.getGeographic_data();
     txtGeographicdata.setText(profileGeographic_data);
    
    String profileDate_of_birth=profile.getDate_of_birth();
    txtDateofbirth.setText(profileDate_of_birth);
    
    String profileTelephone_num=profile.getTelephone_num();
   txtTelephonenumbers.setText(profileTelephone_num);
    
    String profileFAX_num=profile.getFAX_num();
      txtFAXnumber.setText( profileFAX_num);
    
    String profileEmail_address=profile.getEmail_address();
     txtEmailaddresses.setText(profileEmail_address);
    
    String profileSocialSecurity_num=profile.getSocialSecurity_num();
    txtSocialSecuritynumber.setText(profileSocialSecurity_num);
    
    String profileMedicalrecord_num=profile.getMedicalrecord_num();
    txtMedicalrecordnumber.setText( profileMedicalrecord_num);
    
    String profileHealth_plan_beneficiary_num=profile.getHealth_plan_beneficiary_num();
      txtHealthplanbeneficiarynumber.setText(profileHealth_plan_beneficiary_num);
    
    String profileBankaccount_num=profile.getBankaccount_num();
     txtBankaccountnumbers.setText(profileBankaccount_num);
    
    String profileCertificate_license_num=profile.getCertificate_license_num();
    txtCertificatelicensenumber.setText(profileCertificate_license_num);
    
    String profileVehicle_id=profile.getVehicle_id();
    txtVehicleidentifiersandserialnumbersincludinglicenseplates.setText(profileVehicle_id);
    
       String profileDevice_id=profile.getDevice_id();
    txtDeviceidentifiersandserialnumbers.setText(profileDevice_id);
    
       String profileLinkedIn=profile.getLinkedIn();
    txtLinkedIn.setText(profileLinkedIn);
    
       String profileInternet_protocol_addresses=profile.getInternet_protocol_addresses();
    txtInternetprotocoladdresses.setText(profileInternet_protocol_addresses);
    
       String profileAny_unique_identifying_number_characteristic_or_code=profile.getAny_unique_identifying_number_characteristic_or_code();
    txtAnyuniqueidentifyingnumber.setText(profileAny_unique_identifying_number_characteristic_or_code);
    
    String profileAsetBiometric_identifiers=profile.getBiometric_identifiers() ;
    txtBiometricidentifiers.setText(profileAsetBiometric_identifiers);
    
    
    
       
       
        
    
           String path=profile.getPhotopath();
        ImageIcon icon = new ImageIcon(path); 
        image.setIcon(icon);
  
 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFAXnumber = new javax.swing.JLabel();
        lblEmailaddresses = new javax.swing.JLabel();
        lblSocialSecuritynumber = new javax.swing.JLabel();
        lblMedicalrecordnumber = new javax.swing.JLabel();
        lblHealthplanbeneficiarynumber = new javax.swing.JLabel();
        lblBankaccountnumbers = new javax.swing.JLabel();
        lblTelephonenumbers = new javax.swing.JLabel();
        lblCertificatelicensenumber = new javax.swing.JLabel();
        lblVehicleidentifiersandserialnumbersincludinglicenseplates = new javax.swing.JLabel();
        lblDeviceidentifiersandserialnumbers = new javax.swing.JLabel();
        txtEmailaddresses = new javax.swing.JTextField();
        txtSocialSecuritynumber = new javax.swing.JTextField();
        txtMedicalrecordnumber = new javax.swing.JTextField();
        txtHealthplanbeneficiarynumber = new javax.swing.JTextField();
        txtBankaccountnumbers = new javax.swing.JTextField();
        txtCertificatelicensenumber = new javax.swing.JTextField();
        txtVehicleidentifiersandserialnumbersincludinglicenseplates = new javax.swing.JTextField();
        txtDeviceidentifiersandserialnumbers = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtInternetprotocoladdresses = new javax.swing.JTextField();
        lblCreateYourProfile = new javax.swing.JLabel();
        lblDateofbirth = new javax.swing.JLabel();
        txtAnyuniqueidentifyingnumber = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblGeographicdata = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblInternetprotocoladdresses = new javax.swing.JLabel();
        lblAnyuniqueidentifyingnumber = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeographicdata = new javax.swing.JTextField();
        txtDateofbirth = new javax.swing.JTextField();
        txtTelephonenumbers = new javax.swing.JTextField();
        txtFAXnumber = new javax.swing.JTextField();
        lblBiometric_identifiers = new javax.swing.JLabel();
        txtBiometricidentifiers = new javax.swing.JTextField();

        lblFAXnumber.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblFAXnumber.setText("FAX number");

        lblEmailaddresses.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblEmailaddresses.setText("Email addresses");

        lblSocialSecuritynumber.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblSocialSecuritynumber.setText("Social Security number");

        lblMedicalrecordnumber.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblMedicalrecordnumber.setText("Medical record number");

        lblHealthplanbeneficiarynumber.setText("Health plan beneficiary number");

        lblBankaccountnumbers.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblBankaccountnumbers.setText("Bank account numbers");

        lblTelephonenumbers.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblTelephonenumbers.setText("Telephone numbers");

        lblCertificatelicensenumber.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblCertificatelicensenumber.setText("Certificate/license number");

        lblVehicleidentifiersandserialnumbersincludinglicenseplates.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblVehicleidentifiersandserialnumbersincludinglicenseplates.setText("Vehicle identifiers and serial numbers including license plates");

        lblDeviceidentifiersandserialnumbers.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblDeviceidentifiersandserialnumbers.setText("Device identifiers and serial numbers");

        txtHealthplanbeneficiarynumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthplanbeneficiarynumberActionPerformed(evt);
            }
        });

        txtCertificatelicensenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificatelicensenumberActionPerformed(evt);
            }
        });

        lblCreateYourProfile.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        lblCreateYourProfile.setForeground(new java.awt.Color(255, 51, 51));
        lblCreateYourProfile.setText("View Your Profile");

        lblDateofbirth.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblDateofbirth.setText("Date of birth");

        lblName.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblName.setText("Name");

        lblGeographicdata.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblGeographicdata.setText("Geographic data");

        lblLinkedIn.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblLinkedIn.setText("LinkedIn");

        lblInternetprotocoladdresses.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblInternetprotocoladdresses.setText("Internet protocol addresses");

        lblAnyuniqueidentifyingnumber.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblAnyuniqueidentifyingnumber.setText("Any_unique_identifying_number_characteristic_or_code");

        image.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        image.setText("FullFacePhoto");

        txtTelephonenumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephonenumbersActionPerformed(evt);
            }
        });

        lblBiometric_identifiers.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblBiometric_identifiers.setText("Biometric identifiers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblGeographicdata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblDateofbirth)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblFAXnumber)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtFAXnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTelephonenumbers)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTelephonenumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblEmailaddresses)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEmailaddresses))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblSocialSecuritynumber)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSocialSecuritynumber))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblMedicalrecordnumber)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMedicalrecordnumber)))
                                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCertificatelicensenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblBankaccountnumbers)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBankaccountnumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblCreateYourProfile)
                                .addComponent(txtCertificatelicensenumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHealthplanbeneficiarynumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHealthplanbeneficiarynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInternetprotocoladdresses)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInternetprotocoladdresses, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLinkedIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDeviceidentifiersandserialnumbers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDeviceidentifiersandserialnumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVehicleidentifiersandserialnumbersincludinglicenseplates)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVehicleidentifiersandserialnumbersincludinglicenseplates, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAnyuniqueidentifyingnumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnyuniqueidentifyingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBiometric_identifiers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBiometricidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDateofbirth, lblEmailaddresses, lblFAXnumber, lblGeographicdata, lblMedicalrecordnumber, lblName, lblSocialSecuritynumber, lblTelephonenumbers});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDateofbirth, txtEmailaddresses, txtFAXnumber, txtGeographicdata, txtMedicalrecordnumber, txtName, txtSocialSecuritynumber, txtTelephonenumbers});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAnyuniqueidentifyingnumber, lblBankaccountnumbers, lblBiometric_identifiers, lblCertificatelicensenumber, lblDeviceidentifiersandserialnumbers, lblHealthplanbeneficiarynumber, lblInternetprotocoladdresses, lblLinkedIn, lblVehicleidentifiersandserialnumbersincludinglicenseplates});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAnyuniqueidentifyingnumber, txtBankaccountnumbers, txtBiometricidentifiers, txtCertificatelicensenumber, txtDeviceidentifiersandserialnumbers, txtHealthplanbeneficiarynumber, txtInternetprotocoladdresses, txtLinkedIn, txtVehicleidentifiersandserialnumbersincludinglicenseplates});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblCreateYourProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHealthplanbeneficiarynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHealthplanbeneficiarynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGeographicdata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBankaccountnumbers)
                        .addComponent(txtBankaccountnumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGeographicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCertificatelicensenumber)
                        .addComponent(txtCertificatelicensenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephonenumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelephonenumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehicleidentifiersandserialnumbersincludinglicenseplates)
                    .addComponent(txtVehicleidentifiersandserialnumbersincludinglicenseplates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFAXnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFAXnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeviceidentifiersandserialnumbers)
                    .addComponent(txtDeviceidentifiersandserialnumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailaddresses, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailaddresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedIn)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSocialSecuritynumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSocialSecuritynumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInternetprotocoladdresses)
                    .addComponent(txtInternetprotocoladdresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalrecordnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicalrecordnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnyuniqueidentifyingnumber)
                    .addComponent(txtAnyuniqueidentifyingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBiometricidentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBiometric_identifiers))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDateofbirth, lblEmailaddresses, lblFAXnumber, lblGeographicdata, lblMedicalrecordnumber, lblName, lblSocialSecuritynumber, lblTelephonenumbers});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDateofbirth, txtEmailaddresses, txtFAXnumber, txtGeographicdata, txtMedicalrecordnumber, txtName, txtSocialSecuritynumber, txtTelephonenumbers});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAnyuniqueidentifyingnumber, lblBankaccountnumbers, lblBiometric_identifiers, lblCertificatelicensenumber, lblDeviceidentifiersandserialnumbers, lblHealthplanbeneficiarynumber, lblInternetprotocoladdresses, lblLinkedIn, lblVehicleidentifiersandserialnumbersincludinglicenseplates});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAnyuniqueidentifyingnumber, txtBankaccountnumbers, txtBiometricidentifiers, txtCertificatelicensenumber, txtDeviceidentifiersandserialnumbers, txtHealthplanbeneficiarynumber, txtInternetprotocoladdresses, txtLinkedIn, txtVehicleidentifiersandserialnumbersincludinglicenseplates});

    }// </editor-fold>//GEN-END:initComponents

    private void txtHealthplanbeneficiarynumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthplanbeneficiarynumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthplanbeneficiarynumberActionPerformed

    private void txtCertificatelicensenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificatelicensenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificatelicensenumberActionPerformed

    private void txtTelephonenumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephonenumbersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephonenumbersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel lblAnyuniqueidentifyingnumber;
    private javax.swing.JLabel lblBankaccountnumbers;
    private javax.swing.JLabel lblBiometric_identifiers;
    private javax.swing.JLabel lblCertificatelicensenumber;
    private javax.swing.JLabel lblCreateYourProfile;
    private javax.swing.JLabel lblDateofbirth;
    private javax.swing.JLabel lblDeviceidentifiersandserialnumbers;
    private javax.swing.JLabel lblEmailaddresses;
    private javax.swing.JLabel lblFAXnumber;
    private javax.swing.JLabel lblGeographicdata;
    private javax.swing.JLabel lblHealthplanbeneficiarynumber;
    private javax.swing.JLabel lblInternetprotocoladdresses;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalrecordnumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSocialSecuritynumber;
    private javax.swing.JLabel lblTelephonenumbers;
    private javax.swing.JLabel lblVehicleidentifiersandserialnumbersincludinglicenseplates;
    private javax.swing.JTextField txtAnyuniqueidentifyingnumber;
    private javax.swing.JTextField txtBankaccountnumbers;
    private javax.swing.JTextField txtBiometricidentifiers;
    private javax.swing.JTextField txtCertificatelicensenumber;
    private javax.swing.JTextField txtDateofbirth;
    private javax.swing.JTextField txtDeviceidentifiersandserialnumbers;
    private javax.swing.JTextField txtEmailaddresses;
    private javax.swing.JTextField txtFAXnumber;
    private javax.swing.JTextField txtGeographicdata;
    private javax.swing.JTextField txtHealthplanbeneficiarynumber;
    private javax.swing.JTextField txtInternetprotocoladdresses;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalrecordnumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSocialSecuritynumber;
    private javax.swing.JTextField txtTelephonenumbers;
    private javax.swing.JTextField txtVehicleidentifiersandserialnumbersincludinglicenseplates;
    // End of variables declaration//GEN-END:variables

    
}
