/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wang
 */
public class ManageRestaurantAdmin extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurantAdmin
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    /**
     * Creates new form CustomerManagementScreen
     */
    public ManageRestaurantAdmin(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.populate();
    }

    public void populate()
    {
        DefaultTableModel dtm = (DefaultTableModel) tabCustomers.getModel();
        dtm.setRowCount(0);
        for (UserAccount i : this.ecosystem.getUserAccountDirectory().getUserAccountList()) {
            if(i.getRole() instanceof AdminRole)
            {
                Object row[] = new Object[2];
                row[0] = i;
                row[1] = i.getPassword();
                dtm.addRow(row);
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabCustomers = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("微软雅黑", 3, 18)); // NOI18N
        btnBack.setText("<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 115, -1));

        tabCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabCustomers);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 51, 473, 125));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Restaurant Adminstrator Management");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 0, -1, 32));

        btnCreate.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        btnCreate.setText("Create A New Restaurant Administrator");
        btnCreate.setToolTipText("");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 231, -1, -1));

        btnDelete.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        btnDelete.setText("Remove the administrator Info");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 186, -1, -1));

        btnView.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        btnView.setText("Detailed Infomation");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 186, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        this.userProcessContainer.remove(this);
        layout.show(userProcessContainer, "userMain");
        Component[] comps=this.userProcessContainer.getComponents();
        for(Component comp:comps)
        {
            if(comp instanceof SystemAdminWorkAreaJPanel)
            {
                SystemAdminWorkAreaJPanel manage=(SystemAdminWorkAreaJPanel)comp;
                manage.populateTree();
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateRestaurantAdminScreen create=new CreateRestaurantAdminScreen(this.userProcessContainer,this.ecosystem);
        this.userProcessContainer.add("CreateRestaurantAdminScreen",create);
        
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabCustomers.getSelectedRow();

        if (selectedRow >= 0) {
            String username =  tabCustomers.getValueAt(selectedRow, 0).toString();
            if(this.ecosystem.getUserAccountDirectory().removeUserAccount(username))
            {
                JOptionPane.showMessageDialog(null, "Restaurant administrator deleted.");
                this.populate();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Restaurant administrator not exist");
            }
                
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabCustomers.getSelectedRow();

        if (selectedRow >= 0) {
            String username=tabCustomers.getValueAt(selectedRow, 0).toString();
            ViewRestaurantAdminScreen view=new ViewRestaurantAdminScreen(this.userProcessContainer,this.ecosystem,username);
            this.userProcessContainer.add("ViewRestaurantAdminScreen",view);
            CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
            layout.show(this.userProcessContainer, "ViewRestaurantAdminScreen");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabCustomers;
    // End of variables declaration//GEN-END:variables
}
