/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author wang
 */
public class ViewRestaurantAdminScreen extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem ecosystem;
    String username;
    String olduserName;
    /**
     * Creates new form ViewCustomerScreen
     */
    public ViewRestaurantAdminScreen(JPanel rightPanel,EcoSystem system,String username) {
        initComponents();
        this.userProcessContainer=rightPanel;
        this.ecosystem=system;
        this.username=username;
        this.fill();
    }

    public void fill()
    {
        UserAccount ua=this.ecosystem.getUserAccountDirectory().searchUserAccount(username);
        this.txtUsername.setText(ua.getUsername());
        this.txtPassword.setText(ua.getPassword());
        Restaurant res=this.ecosystem.getRestaurantDirectory().searchRestaurantByAdmin(username);
        if(res==null)
            this.txtRestaurantName.setText("");
        else
            this.txtRestaurantName.setText(res.getRestaurantName());
        this.olduserName=ua.getUsername();
        this.txtUsername.setEnabled(false);
        this.txtPassword.setEnabled(false);
        this.txtRestaurantName.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtRestaurantName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setFont(new java.awt.Font("微软雅黑 Light", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 293, 95, -1));

        btnConfirm.setFont(new java.awt.Font("微软雅黑 Light", 1, 14)); // NOI18N
        btnConfirm.setText("Save");
        btnConfirm.setActionCommand("Update");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 293, -1, -1));

        txtUsername.setFont(new java.awt.Font("微软雅黑 Light", 1, 14)); // NOI18N
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 131, 158, -1));

        txtPassword.setFont(new java.awt.Font("微软雅黑 Light", 1, 14)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 178, 158, -1));

        jLabel1.setFont(new java.awt.Font("微软雅黑 Light", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 124, 139, 41));

        txtRestaurantName.setFont(new java.awt.Font("微软雅黑 Light", 1, 14)); // NOI18N
        txtRestaurantName.setToolTipText("Format: mm/dd/yy");
        add(txtRestaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 229, 158, -1));

        jLabel2.setFont(new java.awt.Font("微软雅黑 Light", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 171, 139, 41));

        btnBack.setFont(new java.awt.Font("宋体", 3, 18)); // NOI18N
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("微软雅黑 Light", 1, 14)); // NOI18N
        jLabel3.setText("Name of restaurant");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 222, -1, 41));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Restaurant Adminidstrator's Detailed Infomation");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        this.txtRestaurantName.setEnabled(true);
        this.txtUsername.setEnabled(true);
        this.txtPassword.setEnabled(true);
        //this.btnConfirm.setVisible(true);
        //this.btnUpdate.setVisible(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String username=this.txtUsername.getText();
        String password=this.txtPassword.getText();
        String restName=this.txtRestaurantName.getText();

        if(ecosystem.checkIfUserIsUnique(username))
        {
            JOptionPane.showMessageDialog(null, "Restaurant administrator already exist!");

        }
        else
        {
            ecosystem.getUserAccountDirectory().searchUserAccount(this.olduserName).setUsername(username);
            ecosystem.getUserAccountDirectory().searchUserAccount(username).setPassword(password);
            Restaurant res=ecosystem.getRestaurantDirectory().searchRestaurantByAdmin(olduserName);
            if(res!=null)
            {
                res.setRestaurantName(restName);
                res.removeRestaurantAdmin(olduserName);
                res.addRestaurantAdmin(restName);
            }
            JOptionPane.showMessageDialog(null, "Restaurant administrator updated successfully!");
            this.txtUsername.setEnabled(false);
            this.txtPassword.setEnabled(false);
            this.txtRestaurantName.setEnabled(false);
            //this.btnUpdate.setVisible(true);
            //this.btnConfirm.setVisible(false);
        }

    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
          CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        this.userProcessContainer.remove(this);
        layout.show(userProcessContainer, "ManageRestaurantAdmin");
        Component[] comps=this.userProcessContainer.getComponents();
        for(Component comp:comps)
        {
            if(comp instanceof ManageRestaurantAdmin)
            {
                ManageRestaurantAdmin manage=(ManageRestaurantAdmin)comp;
                manage.populate();
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRestaurantName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
