/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class CreateAccountJPanel extends javax.swing.JPanel {

    private CarDirectory carDirectory;
    private JPanel userProcessContainer;

    /**
     * Creates new form CreateAccountJPanel
     */


    CreateAccountJPanel(JPanel userProcessContainer, CarDirectory carDirectory) {
         //To change body of generated methods, choose Tools | Templates.
            initComponents();
        this.userProcessContainer=userProcessContainer;
        this.carDirectory=carDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateAccount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAvailability = new javax.swing.JTextField();
        txtManufacturer = new javax.swing.JTextField();
        txtProductionYear = new javax.swing.JTextField();
        txtCapacity = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtCurrentCity = new javax.swing.JTextField();
        txtMaintenanceValidation = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCreateAccount = new javax.swing.JButton();

        lblCreateAccount.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        lblCreateAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateAccount.setText("Create Your Account");

        jLabel1.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel1.setText("Availability");

        jLabel2.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel2.setText("Manufacturer");

        jLabel3.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel3.setText("Production Year");

        jLabel4.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel4.setText("Capacity");

        jLabel5.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel5.setText("Serial Number");

        jLabel6.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel6.setText("Model Number");

        jLabel7.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel7.setText("Current City");

        jLabel8.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel8.setText("Maintenance Validation");

        txtAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailabilityActionPerformed(evt);
            }
        });

        txtCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacityActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("宋体", 2, 14)); // NOI18N
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreateAccount.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCurrentCity, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txtModelNumber)
                            .addComponent(txtSerialNumber)
                            .addComponent(txtCapacity)
                            .addComponent(txtProductionYear))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(36, 36, 36)
                                .addComponent(txtMaintenanceValidation))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(36, 36, 36)
                                .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(236, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(lblCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txtManufacturer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtProductionYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(txtCapacity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(txtModelNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(txtCurrentCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtMaintenanceValidation))
                .addGap(18, 18, 18)
                .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel6, jLabel7, jLabel8});

    }// </editor-fold>//GEN-END:initComponents

    private void txtAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailabilityActionPerformed

    private void txtCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacityActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        if(txtAvailability.getText().length()==0||txtManufacturer.getText().length()==0||txtProductionYear.getText().length()==0||txtCapacity.getText().length()==0||txtSerialNumber.getText().length()==0||txtModelNumber.getText().length()==0||txtCurrentCity.getText().length()==0||txtMaintenanceValidation.getText().length()==0||txtAvailability.getText().replaceAll("[0-9]","").length()!=0||txtProductionYear.getText().replaceAll("[0-9]","").length()!=0||txtCapacity.getText().replaceAll("[0-9]","").length()!=0||txtMaintenanceValidation.getText().replaceAll("[0-9]","").length()!=0){
            
            //无输入不是null，表示为长度为0
            JOptionPane.showMessageDialog(null, "Your input is imcomplete or invalid,please try again","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
        
        int availability=Integer.parseInt(txtAvailability.getText());//getText()只能get String
        String manufacturer=txtManufacturer.getText();
        int productionyear=Integer.parseInt(txtProductionYear.getText());
        int capacity=Integer.parseInt(txtCapacity.getText());
        String serialNumber=txtSerialNumber.getText();
        String modelNumber=txtModelNumber.getText();
        String city=txtCurrentCity.getText();
        int maintenanceValidation=Integer.parseInt(txtMaintenanceValidation.getText());
        
        Car car=carDirectory.addCar();
        car.setAvailability(availability);
       car.setManufacturer(manufacturer);
       car.setProduction_Year(productionyear);
       car.setCapacity(capacity);
       car.setSerial_Number(serialNumber);
       car.setModel_Number(modelNumber);
       car.setCity(city);
       car.setMaintenance_Validation(maintenanceValidation);
       
           Car toyota1=carDirectory.addCar();
        toyota1.setAvailability(0);
      toyota1.setManufacturer("Toyota");
      toyota1.setProduction_Year(1980);
       toyota1.setCapacity(2);
       toyota1.setSerial_Number("100");
       toyota1.setModel_Number("1");
       toyota1.setCity("Boston");
       toyota1.setMaintenance_Validation(1);
       
           Car toyota2=carDirectory.addCar();
        toyota2.setAvailability(1);
       toyota2.setManufacturer("Toyota");
       toyota2.setProduction_Year(1990);
       toyota2.setCapacity(5);
      toyota2.setSerial_Number("101");
       toyota2.setModel_Number("2");
       toyota2.setCity("Seattle");
       toyota2.setMaintenance_Validation(0);
       
           Car toyota3=carDirectory.addCar();
       toyota3.setAvailability(1);
       toyota3.setManufacturer("Toyota");
       toyota3.setProduction_Year(2000);
      toyota3.setCapacity(4);
       toyota3.setSerial_Number("102");
      toyota3.setModel_Number("3");
       toyota3.setCity("New York");
       toyota3.setMaintenance_Validation(1);
       
           Car lotus1=carDirectory.addCar();
       lotus1.setAvailability(1);
      lotus1.setManufacturer("Lotus");
       lotus1.setProduction_Year(2010);
       lotus1.setCapacity(2);
       lotus1.setSerial_Number("103");
       lotus1.setModel_Number("1");
       lotus1.setCity("Boston");
       lotus1.setMaintenance_Validation(1);
       
           Car lotus2=carDirectory.addCar();
        lotus2.setAvailability(0);
       lotus2.setManufacturer("Lotus");
       lotus2.setProduction_Year(2020);
       lotus2.setCapacity(2);
       lotus2.setSerial_Number("104");
       lotus2.setModel_Number("2");
       lotus2.setCity("Seattle");
       lotus2.setMaintenance_Validation(1);
       
           Car lexus=carDirectory.addCar();
        lexus.setAvailability(1);
       lexus.setManufacturer("Lexus");
       lexus.setProduction_Year(1980);
       lexus.setCapacity(5);
       lexus.setSerial_Number("105");
       lexus.setModel_Number("2");
       lexus.setCity("Boston");
       lexus.setMaintenance_Validation(0);
       
           Car audi=carDirectory.addCar();
       audi.setAvailability(0);
       audi.setManufacturer("Audi");
      audi.setProduction_Year(1990);
       audi.setCapacity(5);
      audi.setSerial_Number("106");
       audi.setModel_Number("1");
       audi.setCity("Seattle");
       audi.setMaintenance_Validation(0);
       
       
       
           Car Benz1=carDirectory.addCar();
        Benz1.setAvailability(0);
       Benz1.setManufacturer("Benz");
       Benz1.setProduction_Year(2000);
      Benz1.setCapacity(4);
       Benz1.setSerial_Number("107");
       Benz1.setModel_Number("1");
       Benz1.setCity("Seattle");
       Benz1.setMaintenance_Validation(0);
       
           Car Benz2=carDirectory.addCar();
        Benz2.setAvailability(1);
       Benz2.setManufacturer("Benz");
       Benz2.setProduction_Year(1990);
       Benz2.setCapacity(5);
       Benz2.setSerial_Number("108");
       Benz2.setModel_Number("2");
       Benz2.setCity("New York");
       Benz2.setMaintenance_Validation(1);
       
           Car BMW=carDirectory.addCar();
        BMW.setAvailability(0);
       BMW.setManufacturer("BMW");
       BMW.setProduction_Year(2000);
       BMW.setCapacity(2);
       BMW.setSerial_Number("109");
       BMW.setModel_Number("1");
       BMW.setCity("Boston");
       BMW.setMaintenance_Validation(0);
       
       
       
       
        
        JOptionPane.showMessageDialog(null, "Account Created Successfully");
        }
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtCurrentCity;
    private javax.swing.JTextField txtMaintenanceValidation;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtProductionYear;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
