/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author wang
 */
public class CreateMenuScreen extends javax.swing.JPanel {

   JPanel userProcessContainer;
    EcoSystem ecosystem;
    Restaurant res;
    /**
     * Creates new form CreateCustomerScreen
     */
    public CreateMenuScreen(JPanel userProcessContainer,EcoSystem ecosystem,String resName) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.res=this.ecosystem.getRestaurantDirectory().searchRestaurantByName(resName);
        if(this.res==null)
            JOptionPane.showMessageDialog(null, "System error occurred! Please log out!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDishname = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtResaurantName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtDishname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 177, 158, -1));
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 216, 158, -1));

        txtResaurantName.setToolTipText("Format: mm/dd/yy");
        add(txtResaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 138, 158, -1));

        jLabel1.setFont(new java.awt.Font("微软雅黑", 3, 14)); // NOI18N
        jLabel1.setText("Name of Dish");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 179, 146, -1));

        jLabel2.setFont(new java.awt.Font("微软雅黑", 3, 14)); // NOI18N
        jLabel2.setText("Selling Price");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 216, 146, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Create new menu");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 73, -1, -1));

        btnBack.setFont(new java.awt.Font("宋体", 3, 18)); // NOI18N
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 109, 42));

        jLabel3.setFont(new java.awt.Font("微软雅黑", 3, 14)); // NOI18N
        jLabel3.setText("Name of Restaurant ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 138, -1, -1));

        btnCreate.setFont(new java.awt.Font("微软雅黑 Light", 3, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.setActionCommand("Update");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 259, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        this.userProcessContainer.remove(this);
        Component[] comps=this.userProcessContainer.getComponents();
        for(Component comp:comps)
        {
            if(comp instanceof ManageMenu)
            {
                ManageMenu manageP=(ManageMenu)comp;
                manageP.populate();
            }
        }
        layout.show(this.userProcessContainer, "ManageMenu");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String dishname=this.txtDishname.getText();
        String priceStr=this.txtPrice.getText();

        try {
            Double.parseDouble(priceStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, priceStr + " is not a valid number.");
        }
        double price=Double.parseDouble(priceStr);
        if(this.res.addMenu(dishname, price))
        {
            this.txtDishname.setText("");
            this.txtPrice.setText("");
            JOptionPane.showMessageDialog(null, "Menu created successfully!");
        }
        else
        JOptionPane.showMessageDialog(null, "Menu already exist!");

        
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDishname;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtResaurantName;
    // End of variables declaration//GEN-END:variables
}
