/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Order;
import Business.Restaurant.OrderItem;
import Business.Role.DeliverManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wang
 */
public class ProcessOrderScreen extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem ecosystem;
    Order order;
    /**
     * Creates new form CustomerManagementScreen
     */
    public ProcessOrderScreen(JPanel userProcessContainer,EcoSystem ecosystem,Order order) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.order=order;
        this.populateDetail();
        this.populateDeliveryMen();
     
        //this.txtComment.setEnabled(false);
        //this.txtComment.setText(this.order.getComment());
//        
//        if(this.order.getDeliveryManName()!=null&&!this.order.getDeliveryManName().equals(""))
//            this.lblDeliveryMan.setText(this.order.getComment());
//        if(this.order.getStatus().equals("Commented"))
//            this.btnAssign.setVisible(false);

    }
    public void populateDetail()
    {
        DefaultTableModel dtm = (DefaultTableModel) tabOrders.getModel();
        dtm.setRowCount(0);
        for (OrderItem i:this.order.getItems()) {
                Object row[] = new Object[2];
                row[0] = i.getDishAndPrice().getDishName();
                row[1] = i.getDishAndPrice().getPrice();
                dtm.addRow(row);
        }
    }
    
    public void populateDeliveryMen()
    {
        DefaultTableModel dtm = (DefaultTableModel) tabDeliveryMen.getModel();
        dtm.setRowCount(0);
        for (UserAccount i : this.ecosystem.getUserAccountDirectory().getUserAccountList()) {
            if(i.getRole() instanceof DeliverManRole)
            {
                Object row[] = new Object[1];
                row[0] = i;
                dtm.addRow(row);
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssign = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabOrders = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabDeliveryMen = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAssign.setFont(new java.awt.Font("宋体", 3, 14)); // NOI18N
        btnAssign.setText("Select a deliveryman to distribute");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 337, 315, -1));

        btnBack.setFont(new java.awt.Font("微软雅黑 Light", 3, 18)); // NOI18N
        btnBack.setText("<back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 104, -1));

        tabOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dish", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabOrders);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 57, 510, 102));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("All of the DeliveryMen");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 169, -1, 32));

        tabDeliveryMen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabDeliveryMen);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 207, 510, 99));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setText("All the Orders ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 10, -1, 32));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabDeliveryMen.getSelectedRow();

        if (selectedRow >= 0) {
            UserAccount item = (UserAccount) tabDeliveryMen.getValueAt(selectedRow,0);
            this.order.setDeliveryManName(item.getUsername());
            this.order.setStatus("Delivery man assigned");
            
            JOptionPane.showMessageDialog(null, "Delivery man assigned!");
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        this.userProcessContainer.remove(this);
        layout.show(userProcessContainer, "ManageOrder");
    }//GEN-LAST:event_btnBackActionPerformed

    private void tabOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabOrdersMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tabOrdersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabDeliveryMen;
    private javax.swing.JTable tabOrders;
    // End of variables declaration//GEN-END:variables
}
