/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.MenuItem;
import Business.Restaurant.Restaurant;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author wang
 */
public class ViewMenu extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem ecosystem;
    MenuItem item;
    String oldDishName;
    Restaurant res;
    /**
     * Creates new form ViewCustomerScreen
     */
    public ViewMenu(JPanel rightPanel,EcoSystem system,String resName,MenuItem item) {
        initComponents();
        this.userProcessContainer=rightPanel;
        this.ecosystem=system;
        this.oldDishName=item.getDishName();
        this.item=item;
        this.fill();
        this.res=this.ecosystem.getRestaurantDirectory().searchRestaurantByName(resName);
        if(this.res==null)
            JOptionPane.showMessageDialog(null, "System error occurred! Please log out!");
        //this.btnConfirm.setVisible(false);
    }
    public void fill()
    {
        this.txtDishname.setText(this.item.getDishName());
        this.txtPrice.setText(Double.toString(this.item.getPrice()));
        this.txtDishname.setEnabled(false);
        this.txtPrice.setEnabled(false);
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDishname = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtDishname, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 71, 158, -1));
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 98, 158, -1));

        jLabel1.setFont(new java.awt.Font("微软雅黑", 2, 14)); // NOI18N
        jLabel1.setText("Name of the Dish");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 71, 137, -1));

        jLabel2.setFont(new java.awt.Font("微软雅黑", 2, 14)); // NOI18N
        jLabel2.setText("Current Selling Price");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 100, -1, -1));

        btnBack.setFont(new java.awt.Font("微软雅黑 Light", 3, 18)); // NOI18N
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Detailed Menu Info");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 5, 190, -1));

        btnUpdate.setFont(new java.awt.Font("楷体", 2, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 95, -1));

        btnConfirm.setFont(new java.awt.Font("楷体", 2, 14)); // NOI18N
        btnConfirm.setText("Save");
        btnConfirm.setActionCommand("Update");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardLayout layout=(CardLayout)this.userProcessContainer.getLayout();
        this.userProcessContainer.remove(this);
        layout.show(userProcessContainer, "ManageMenu");
        Component[] comps=this.userProcessContainer.getComponents();
        for(Component comp:comps)
        {
            if(comp instanceof ManageMenu)
            {
                ManageMenu manage=(ManageMenu)comp;
                manage.populate();
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.txtDishname.setEnabled(true);
        this.txtPrice.setEnabled(true);
        //this.btnConfirm.setVisible(true);
        //this.btnUpdate.setVisible(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String dishname=this.txtDishname.getText();
        String priceStr=this.txtPrice.getText();

        try {
            Double.parseDouble(priceStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, priceStr + " is not a valid number.");
        }
        double price=Double.parseDouble(priceStr);
        if(this.res.updateMenu(oldDishName,dishname, price))
        {
            JOptionPane.showMessageDialog(null, "Menu updated successfully!");
            this.txtDishname.setEnabled(false);
            this.txtPrice.setEnabled(false);
            //this.btnUpdate.setVisible(true);
            //this.btnConfirm.setVisible(false);
        }

    }//GEN-LAST:event_btnConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDishname;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
